### ISSUE TITLE
[Feature Request] Display grid view with chapter images' thumbnails, to quickly visualize and search images

### ISSUE THREAD

**Issue by lucky777709** [jobobby04/TachiyomiSY#358] opened 2021-06-14 23:42 UTC
## Why/User Benefit/User Problem
After I opened a gallery chapter, it would be easier to visualize and search for specific images (like in file/image explorers), instead of scrolling them one by one, or having to scroll the "page navigation bar" to a certain number (without knowing the image that will be loaded, or if you are close to a certain image).
This would be especially useful when I'm seeing a gallery for the first time, to have a quick glance at most/all of its images. This would also avoid the user having to remember specific page numbers of favorite images, etc.

## What/Requirements
After opening a gallery chapter, tap the screen to show the navigation bar and the bottom bar options (Chapters, Open in WebView, Crop borders, etc.).
At the bottom bar (or even on the left of the navigation bar), it could have an additional icon to "Show Grid View".
Clicking that icon would display a grid view with the chapter's currently loaded pages (and lower quality thumbnails of other unloaded pages, if possible), it would be an alternate way to navigate the chapter images.

**Comment by joseph619** [comment] 2021-06-15 05:31
Duplicate of #88

**Closed** 2021-06-15 05:33 UTC
