### ISSUE TITLE
TachiSY Keeps Losing Downloads

### ISSUE THREAD

**Issue by Lacaillex** [jobobby04/TachiyomiSY#1075] opened 2024-02-09 17:12 UTC
### Steps to reproduce

1. Download chapter
2. Chapter appears in files, may or not show as downloaded in app
3. If it initially appeared, it will stop showing shortly after
4. Go to advanced settings and invalidate download index
5. All downloads reappear
6. Within a couple minutes all downloads disappear again

### Expected behavior

When things are downloaded, they should appear as downloaded and the series should show when "Downloaded only" is selected.

### Actual behavior

Series only appear for a brief period, then it acts like there are no downloads. 

### Tachiyomi version

1.10.2

### Android version

14

### Device

Samsung Galaxy S23 Ultra

### Other details

I shifted over to TachiyomiSY from Tachiyomi a couple weeks ago, all downloads are stored and pulled from that original download location. For the first couple weeks everything worked fine. This issue has only arisen over the last few days. No settings have been changed during that time. This issue is not restricted to a single series or extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment] 2024-02-11 15:31
Have you checked if the app still has Folder Access permission?

**Comment by jobobby04** [comment] 2024-02-22 19:45
Duplicate of https://github.com/jobobby04/TachiyomiSY/issues/931

**Closed by jobobby04** 2024-02-22 19:45 UTC
Labels: Bug
