### ISSUE TITLE
[Feature Request] Clean Manga Titles

### ISSUE THREAD

**Issue by sethazazel** [jobobby04/TachiyomiSY#60] opened 2020-07-11 16:56 UTC
### Why/User Benefit/User Problem
Current titles are too complicate. (Nhentai)
example : (C92) [Inariya (Inari)] Kyoudai ni Okeru Seikoushou no Kiroku [English] [desudesu]

### What/Requirements
It would be better if we had an option for clean titles.
example : Kyoudai ni Okeru Seikoushou no Kiroku

(Tachiyomi app clean titles but it cause some problems like empty titles. I opened an issue in tachiyomi extensions for this but no one respond yet.)

**Comment by joseph619** [comment] 2020-07-12 04:05
Duplicate of #3 , which is already implemented

**Comment by jobobby04** [comment] 2020-07-12 04:11
Hmm, though this gives me a idea, maybe I could try to implement a quick clean for E/Exh + nHentai + hitomi

**Comment by sethazazel** [comment] 2020-07-12 08:14
I saw the other request but it's not exact same with this. Editing one by one could solve this but it will take too much time if you have a lot of mangas.

**Comment by jobobby04** [comment] 2020-08-05 22:27
Added with https://github.com/jobobby04/TachiyomiSY/commit/44c9df8c9b0974e86bdf8f1c54b5097e7e5d18df
This will be closed when the next release happens

**Comment by sethazazel** [comment] 2020-08-06 08:57
I tried and it works perfectly. Thank you very much.

**Closed** 2020-08-12 20:16 UTC
Labels: will close next release
