### ISSUE TITLE
Title not updating when refreshing, adding or readding the entry

### ISSUE THREAD

**Issue by Ramzh** [jobobby04/TachiyomiSY#638] opened 2022-07-27 16:42 UTC
### Steps to reproduce

1. Find ExHentai entry with ongoing updates in library e.g. [Ahemaru] NTR na Sekai | NTR World Ch 1-5
2. When entry gets new chapters, refreshing should pull the latest update OR when readding the new entry from source
3. Remove the previous entry from library and add the new one, then pull for refresh
4. Migrating from the old entry to the new one still results in the old title (it does crash the app and in the library at first seems like the new title it's there but as soon as you requery the title via sort, search or other means, it will show the old title again)

### Expected behavior

After updating, migrating, adding the updated entry to the library or removing the old entry from library and readding the new updated entry to the library from source, the title should be updated

### Actual behavior

Does not update the title

### Tachiyomi version

preview r464

### Android version

Android 10

### Device

OnePlus 7 Pro

### Other details

[Refresh video](https://cdn.discordapp.com/attachments/732400486241665144/1001886980214370424/22-07-27-17-19-20.mp4
)

I can record the other examples in the steps to reproduce if needed 

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment] 2022-07-28 22:54
Found the cause of this, will be fixed for the next build 👍

**Closed** 2022-07-29 00:14 UTC
Labels: Bug
