### ISSUE TITLE
'Preserve reading position on read manga' not working for Exhentai gallery updates

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#642] opened 2022-07-31 08:27 UTC
### Steps to reproduce

1. Open an ongoing Ehentai/Ex-hentai gallery with multiple chapters/versions
2. Refresh the gallery when there's have a new update

### Expected behavior

The new chapter/version should preserve the reading position from the previous chapter

### Actual behavior

It doesn't preserve the page number, shows as blank unread chapter

### Tachiyomi version

471

### Android version

Android 12

### Device

Galaxy S10+

### Other details

The issue started from 457 onwards after manga info screen was rewritten to compose, and has been broken since

Screenshot 

![Screenshot_20220731-042105](https://user-images.githubusercontent.com/34897862/182017409-9d1106ae-16b2-4cbf-9f9b-7e20e6fb0d6b.jpg)

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment] 2022-07-31 14:47
Its caused by a main Tachi bug, will be fixed for the next preview 👍

**Closed by jobobby04** 2022-07-31 14:47 UTC
Labels: Bug

**Comment by joseph619** [comment] 2022-07-31 15:17
Nice to know, I had to stop reading some ongoing western comics for a couple of months because of this. Thanks mate :)
