### ISSUE TITLE
The return of the random crash when resuming the app after a while

### ISSUE THREAD

**Issue by curche** [jobobby04/TachiyomiSY#934] opened 2023-08-17 02:23 UTC
### Steps to reproduce

1. Use the app for a while
2. Keep it in recents and go use other apps
3. Come back to the app or try to open the app by clicking on the icon in menu

### Expected behavior

App resumes and can be used to read or browse

### Actual behavior

App crashed

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/12364802/tachiyomi_crash_logs.txt)
```
--------- beginning of crash
08-14 22:26:33.793 18313 18313 E AndroidRuntime: FATAL EXCEPTION: main
08-14 22:26:33.793 18313 18313 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 18313
08-14 22:26:33.793 18313 18313 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.kanade.tachiyomi.sy/eu.kanade.tachiyomi.ui.main.MainActivity}: java.lang.NullPointerException: source = null, SOURCE_ID = source_id
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8757)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: Caused by: java.lang.NullPointerException: source = null, SOURCE_ID = source_id
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.extension.details.SourcePreferencesFragment.onCreatePreferences(SourceFile:200)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at androidx.preference.PreferenceFragmentCompat.onCreate(SourceFile:72)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreate(SourceFile:27)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.create(SourceFile:41)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:137)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(SourceFile:88)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:34)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreate(SourceFile:29)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.activity.BaseActivity.onCreate(SourceFile:98)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity.onCreate(SourceFile:30)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8591)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8570)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
08-14 22:26:33.793 18313 18313 E AndroidRuntime: 	... 12 more
--------- beginning of main
App version: 1.9.3 (standard, 119d3ef56, 55, 2023-08-13T19:19Z)
Preview build: 528
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014.N770FXXU9HWF1
Device brand: samsung
Device manufacturer: samsung
Device name: r7
Device model: SM-N770F
Device product name: r7nsxx
```

### Tachiyomi version

528

### Android version

13

### Device

Galaxy Note 10 Lite

### Other details

I added the part of the crashlogs that I thought might be relevant but do note that there are other crashes in the file

This used to happen in a few preview versions before but then was fixed iirc 
Looks like it is now back

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment] 2023-10-01 20:46
Duplicate of #931

**Closed by jobobby04** 2023-10-01 20:46 UTC
Labels: Bug
