### ISSUE TITLE
E-hentai and Exhentai shows a limit of content

### ISSUE THREAD

**Issue by angordrillo** [jobobby04/TachiyomiSY#737] opened 2022-11-21 04:44 UTC
### Steps to reproduce

1. Open the app
2. Go to explore (or gallerys, or browse. I have the app in Spanish so I don't know what's its name in the English version) 
3. Open E-hentai 
4. Scroll down to search for content you'll see its ok and it goes down and down 
5. Search for something that has a lot of entries/Manga/comic
6. When you go down, it stops at some point and it doesn't charge new entries
7. Enable the filter reverse search
8. It'll appear an message That says length=0;index=2

### Expected behavior

It should search and scroll down until it finds no entries, no stop and don't charge more

### Actual behavior

I can't search for new content

### Tachiyomi version

1.8.5

### Android version

10

### Device

HUAWEI P smart z 2019

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment] 2022-11-24 20:03
Its fixed in the preview currently

**Comment by jobobby04** [comment] 2022-11-24 20:08
Also duplicate of #722

**Closed by jobobby04** 2022-11-24 20:08 UTC
Labels: Bug
