### ISSUE TITLE
Cannot manually type manga name when doing manga merge

### ISSUE THREAD

**Issue by Compilatorem** [jobobby04/TachiyomiSY#537] opened 2022-02-26 03:08 UTC
### Steps to reproduce

1. Select your manga and choose the "Merge" button
2. Select an alternative source for that manga
3. If the manga merge result showing is incorrect. You cannot manually type the correct manga name.

https://user-images.githubusercontent.com/100454548/155826564-4e3f9061-bfb4-47be-8ebe-769e3a9d6675.mp4

### Expected behavior

When merging manga and the merge feature find the incorrect manga. You should be able to manually type the manga name to search.

### Actual behavior

Tachiyomi finding the wrong manga and I can't manually type the correct one.

### Tachiyomi version

Preview r441

### Android version

Android 11

### Device

Xiaomi Mi 10T Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment] 2022-02-26 03:11
Duplicate of #446

**Closed by jobobby04** 2022-02-26 03:11 UTC
Labels: Bug
