### ISSUE TITLE
Exhentai not loading again 

### ISSUE THREAD

**Issue by SpoiledMysteryMeat** [jobobby04/TachiyomiSY#1329] opened 2024-11-19 23:35 UTC
### Steps to reproduce

Any attempt to open an exhentai gallery recreates the issues seen in #1293, even in the dev build.

I do not know how to reopen tickets here, sorry!

### Expected behavior

I open the gallery and see things load

### Actual behavior

I am greeted with a blank page and no content loaded

### TachiyomiSY version

v8.8.2

### Android version

android 14

### Device

SM-A526U

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment] 2024-11-20 00:00
Duplicate of https://github.com/jobobby04/TachiyomiSY/issues/1327

> v8.8.2

This is not SY lol.
But anyways, Exhentai recently invalidated a lot of user cookies so you need to logout and login to fix this(Disable and enable Exhentai).

**Closed by jobobby04** 2024-11-20 00:00 UTC
Labels: Bug
