### ISSUE TITLE
Crash when trying to merge a source

### ISSUE THREAD

**Issue by mag0bei** [jobobby04/TachiyomiSY#597] opened 2022-05-04 07:30 UTC
### Steps to reproduce

1- Add a manga to your library
2- in the manga information click then on merge
3- Choose a source to merge to your manga. Once you click on the source the app crashes

### Expected behavior

The app should search in the source or find the manga in the source

### Actual behavior

The application crashes instantly

### Crash logs

[tachiyomi_crash_logs (1).txt](https://github.com/jobobby04/TachiyomiSY/files/8618542/tachiyomi_crash_logs.1.txt)

### Tachiyomi version

TachiyomiSY Preview r453

### Android version

Android 11

### Device

Sony Xperia 5 Mark II

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment] 2022-05-04 15:16
Found the cause of this, will be fixed in the next build

**Closed** 2022-05-10 17:27 UTC
Labels: Bug
