### ISSUE TITLE
Reader going back to first page when rotating device

### ISSUE THREAD

**Issue by Mizotizoi** [jobobby04/TachiyomiSY#788] opened 2023-02-05 20:27 UTC
### Steps to reproduce

Bug from previous tachiyomi version its now on SY
Open some continuous comic in landscape, navigate down, then rotate the device and its gonna send you to the first page. 

### Expected behavior

Rotate and keeps the same page. 

### Actual behavior

Rotate device and send you to the first page

### Tachiyomi version

App version: 1.9.0 (standard, d24a8d2, 46, 2023-02-04T23:26Z) Preview build: 0 Android version: 12 (SDK 32) Android build ID: SP2A.220505.002 Device brand: POCO Device manufacturer: Xiaomi Device name: alioth Device model: M2012K11AG Device product name: aosp_alioth

### Android version

Android 12

### Device

Poco F3

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment] 2023-02-05 20:32
Duplicate of https://github.com/jobobby04/TachiyomiSY/issues/783

**Closed by jobobby04** 2023-02-05 20:32 UTC
Labels: Bug
