### ISSUE TITLE
Crashes on Boot

### ISSUE THREAD

**Issue by Wigsinator** [jobobby04/TachiyomiSY#1163] opened 2024-04-23 19:42 UTC
### Steps to reproduce

Open app from Launcher

### Expected behavior

Opens Normally

### Actual behavior

Opens to library screen with faded thumbnails, does not respond to touch. After a few seconds, crashes to a black screen. If reopened, an Android Error Message pops up saying that Tachiyomi Keeps Stopping.

### Crash logs

```
2024-04-23 15:33:10.168 E/GlobalExceptionHandler: java.lang.IllegalStateException: scroll observation scope does not exist
at androidx.work.CoroutineWorker$$ExternalSyntheticLambda0.run$androidx$compose$ui$contentcapture$AndroidContentCaptureManager$$InternalSyntheticLambda$2$29484e630669854f791886d414d611f34252a816fc574150be2de4c0841480a1$0(SourceFile:314)
at androidx.work.CoroutineWorker$$ExternalSyntheticLambda0.run(SourceFile:3034)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8501)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

### TachiyomiSY version

1.10.5

### Android version

Android 14

### Device

Google Pixel 6

### Other details

I cannot update extensions, as I cannot open the app.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [ ] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by takase1121** [comment] 2024-04-24 00:14
I have the same problem, I restarted my phone and the issue goes away. After a while, it came back.

**Comment by Thehail** [comment] 2024-04-24 09:01
Same problem. I use a Google Pixel 8, maybe its related to that?

**Comment by Foxwell24** [comment] 2024-04-24 10:23
Same issue, pixel 7 pro.
To add, I can hold the icon and select library, updates, history, and browse. This does open the app into the expected page, however app is still unresponsive and crashes after about 10 seconds.

**Comment by sapostoluk** [comment] 2024-04-24 12:18
Same issue, also on Pixel 7 Pro (running Android 14 with the April 2024 security update). Only started the other day. Clearing app cache and storage does not resolve the issue. Like takase1121, I got it to work again after a phone restart, but that only works for so long.

**Comment by Sai-Aheesh** [comment] 2024-04-24 15:25
Same issue, pixel 6. Looks like the latest Android update is causing it.

**Comment by jobobby04** [comment] 2024-04-24 15:27
Duplicate of #1139 and its fixed in the preview version

**Closed by jobobby04** 2024-04-24 15:27 UTC
Labels: Bug
