### ISSUE TITLE
My update manga option doesn't work

### ISSUE THREAD

**Issue by Granthd** [jobobby04/TachiyomiSY#528] opened 2022-02-12 13:48 UTC
### Steps to reproduce
1. Go to updates
2. Refresh Library
3. A warning should pop up

### Expected behavior

When I update my library, I should have all the new manga in the updated section. But it doesn't work. I have over 1200+ manga in my library but doesn't update. And it only shows 100 manga in the update bar when I refresh. I should have all the recent manga in this tab but it doesn't update in the most recent version. But it shows the text on the bottom and doesn't update anything.
![Screenshot_20220212-214226](https://user-images.githubusercontent.com/99542420/153713797-e090f87f-6d02-4041-a633-8d8a34a186b7.jpg)

### Actual behavior

Nothing is happening and I don't have any updates on my manga library on this version.

### Tachiyomi version

1.81

### Android version

Android 11

### Device

Tecno Pova 2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment] 2022-02-12 14:25
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/6599

**Closed** 2022-02-12 14:25 UTC
Labels: Bug
