### ISSUE TITLE
[Feature Request] <Remove from tracking (J2K)>

### ISSUE THREAD

**Issue by e-shl** [jobobby04/TachiyomiSY#341] opened 2021-05-30 16:45 UTC
## What/Requirements
Add  [Also remove from "tracks-name"] from J2K (removing unnecessary manga from the site tracking)
<img src="https://user-images.githubusercontent.com/35057681/120112565-d3090580-c18f-11eb-85f3-14fd08a80816.JPG" width="200" /><img src="https://user-images.githubusercontent.com/35057681/120112572-d43a3280-c18f-11eb-8092-6d7d9f3a5f07.JPG" width="200" /><img src="https://user-images.githubusercontent.com/35057681/120112573-d43a3280-c18f-11eb-8ed5-b2945552ccbf.JPG" width="200" />

**Comment by joseph619** [comment] 2021-06-02 18:35
Duplicate of #92 @jobobby04

**Closed** 2021-06-02 18:35 UTC
