### ISSUE TITLE
Offer by default a search result when we Merge mangas

### ISSUE THREAD

**Issue by mag0bei** [jobobby04/TachiyomiSY#691] opened 2022-09-20 19:33 UTC
### Describe your suggested feature

Whenever we tap the "Merge" button (or choose "Merge" in the overflow menu) on a manga page and choose a source, the app performs a search in the choosen source.
If we're lucky, it will find the right result. If not, the app will try to force a merge with a random manga with no options to change the result 
It would be great for the "Merge" feature that the app presents us with a search result by default instead of trying to force a manga on us.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment] 2022-09-20 19:34
Duplicate of https://github.com/jobobby04/TachiyomiSY/issues/446

**Closed by jobobby04** 2022-09-20 19:34 UTC
Labels: Feature request
