### ISSUE TITLE
[Feature Request] Change app name and colour to suit manga reading mood. 

### ISSUE THREAD

**Issue by afterdelight** [jobobby04/TachiyomiSY#129] opened 2020-10-08 12:10 UTC
Change application name and color to something more suitable to manga reading mood such as for example: Neko from other tachiyomi fork with its cat logo and green color really enhanced my mood to read and makes me feel zen but too bad its only focused on mangadex and have less features. 

On the other side this application colour(bad color combination) and logo(ugly logo), also the app name's initial reminded me of one of my ex's name and it really turned my mood off. Also it has a bad name for a fork. Sorry if this too personal and offended you, cheers!

**Comment by joseph619** [comment] 2020-10-08 19:07
Duplicate of #39

**Closed** 2020-10-08 19:08 UTC
