### ISSUE TITLE
CRASH 

### ISSUE THREAD

**Issue by makoto-kokoroki** [jobobby04/TachiyomiSY#813] opened 2023-03-10 04:31 UTC
### Steps to reproduce

App seems to crash when adding to library after extended period of time or crashes when restoring the library after an extended period of time.  Though I'm no doctor and thus have no idea why it actually occurs. So my steps to reproduce this might not actually work. 

1. I open the app to browse
2. Save items to library for a period of time
3. Eventually one is met with a crash log 
4. The same happens again if I go to restore the app via backup
5. The time of length it takes before this crash occurs is around 10-20m

### Expected behavior

I cannot say for sure the things I am doing in the app are why this crash happens. 

### Actual behavior

This happens when I am doing basic things. But my library is quite enormous. This could be the reason why but I don't know.

### Crash logs

#
[2023-03-09-release.log](https://github.com/jobobby04/TachiyomiSY/files/10938511/2023-03-09-release.log)

### Tachiyomi version

1.9.0

### Android version

Android 13

### Device

Z Fold 4

### Other details

My apologies if my steps are not reasonable. There just isn't much happening when this does occur. I hope the logs can provide some clarity.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by makoto-kokoroki** [comment] 2023-03-10 16:17
I forgot to add that this was running on a work profile made on android 13. So that might have a lot to do with why this occurred. Today I ran the app on the main profile for the device and it is seemingly running with no error; I will report back if this changes.

**Comment by jobobby04** [comment] 2023-03-16 22:12
Duplicate of #812

**Closed by jobobby04** 2023-03-16 22:12 UTC
Labels: Bug
