### ISSUE TITLE
Filters in category not showing new unread manga in last few preview releases

### ISSUE THREAD

**Issue by molitar** [jobobby04/TachiyomiSY#660] opened 2022-08-18 02:15 UTC
### Steps to reproduce

I have some categories created.

No Category - Default
Category - Manual
Category - Hentai

In category manual I have about 5 manhwa that do not update often so I just check them every few days instead of having it check every so many hours.  I have default view to show unread.

I do a manual scan in the category Manual and the pull down report shows that I have a new unread for Murim Login but it does not show in it at all.  I toggle the view still does not show I have to re-open the app or go to filters and turn off filter unread to access it. 

### Expected behavior

New manhwa should show the unread with badge count when new chapters detected.

### Actual behavior

New manhwa should show when scanned but they the filter acts like there is no unread and this ONLY happens for manhwa that is in a category the default no category works fine. 

### Tachiyomi version

Preview R474

### Android version

Android 9

### Device

Oneplus 6T

### Other details

The problem started happening 3 previews previously thought it would be fixed by now as I reported it in the Discord support channel while I was sick.  This happens with preview release.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment] 2022-08-18 02:31
Ya the main Tachi library rewrite isn't fully complete. Basically the issue is that while the item does get the new unread count, it doesn't display it until the view is reloaded.
Closing since it's a main Tachi bug

**Closed by jobobby04** 2022-08-18 02:31 UTC
Labels: Bug
