### ISSUE TITLE
Crash/Freeze on Start until reboot

### ISSUE THREAD

**Issue by s1mml** [jobobby04/TachiyomiSY#1169] opened 2024-04-30 14:14 UTC
### Steps to reproduce

1. Open App
2. Freeze
3. Reboot phone
4. Works again until next day or so

### Expected behavior

App should open 

### Actual behavior

When I want to open the app, I see the library greyed out and everything is frozen. Closing the app and reopening after that doesn't show anything.

### TachiyomiSY version

1.10.5

### Android version

14

### Device

Pixel 6a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment] 2024-04-30 14:15
Duplicate of https://github.com/jobobby04/TachiyomiSY/issues/1139

**Closed by jobobby04** 2024-04-30 14:15 UTC
Labels: Bug
