### ISSUE TITLE
[Preview Version] Allow merging in the library between multiple manga

### ISSUE THREAD

**Issue by AethersKz** [jobobby04/TachiyomiSY#501] opened 2022-01-10 05:54 UTC
### Describe your suggested feature

to be able to merge the manga directly from the library.
![IMG_20220110_003750_544](https://user-images.githubusercontent.com/96607644/148723311-6ec4060b-032c-4c39-9ed7-91644e346afa.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by joseph619** [comment] 2022-02-13 08:19
Likely duplicate of #455

**Comment by jobobby04** [comment] 2022-02-26 03:10
Duplicate of #455

**Closed by jobobby04** 2022-02-26 03:10 UTC
Labels: Feature request
