### ISSUE TITLE
The Update tab doesn't refresh new manga

### ISSUE THREAD

**Issue by Granthd** [jobobby04/TachiyomiSY#529] opened 2022-02-12 15:42 UTC
### Steps to reproduce

1. Go the updates option
2. Refresh Page
3. There should be a warning pop up

### Expected behavior

When I was refreshing to update for recent manga the updates dont show, when it should update to new chapters of manga in my library. I have 1200+ manga in my library and its for frustrating to manual browse. This is an issue since I updated the app to the new version. Please Fix.
![Screenshot_20220212-214248](https://user-images.githubusercontent.com/99542420/153717841-8f93208b-0fe7-470c-8b7f-f9c3628d8cd3.jpg)

### Actual behavior

The update library doesn't show new manga chapters.

### Tachiyomi version

1.81

### Android version

Android 11

### Device

Tecno Pova 2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment] 2022-02-12 15:46
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/6599

**Closed by jobobby04** 2022-02-12 15:46 UTC
Labels: Bug
