### ISSUE TITLE
[Feature Request] Sort of  history updates 

### ISSUE THREAD

**Issue by ishai8** [jobobby04/TachiyomiSY#260] opened 2021-04-06 06:55 UTC
An option to sort the update log of Manga that each title will only receive one line (and no more, if there multiple chapters) 

Sometimes there is long title that takes time to scroll the antire update log when it is loaded so that sometimes there are updates that are pushed back

**Comment by joseph619** [comment] 2021-04-06 10:20
duplicate of #81

**Closed** 2021-04-06 15:30 UTC
