### ISSUE TITLE
Extension Search performance is abysmally slow

### ISSUE THREAD

**Issue by starscream00** [jobobby04/TachiyomiSY#1158] opened 2024-04-15 23:40 UTC
### Steps to reproduce

- Open SY
- Select an extension 
- Randomly search a manga
- Wait

### Expected behavior

The search shouldn't take more than 10 seconds like in J2K as in the first video

https://github.com/jobobby04/TachiyomiSY/assets/67589622/f7f83beb-e580-4d92-9041-0b5ddd5b69d6

### Actual behavior

The search took more than a minute in SY same search and extension

https://github.com/jobobby04/TachiyomiSY/assets/67589622/70d64c0e-f9bb-45d4-9433-d2c7bcc04a76

### TachiyomiSY version

1.10.5

### Android version

10

### Device

Lenovo x606f

### Other details

The app is slow. Updating to preview doesn't fix it. The network is idle for a long time. Watch the wifi icon in the second video closely.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment] 2024-05-05 02:34
Duplicate of #1130

**Closed by jobobby04** 2024-05-05 02:34 UTC
Labels: Bug
