### ISSUE TITLE
[Bug] E-Hentai/ExHentai duplicate search results when yousing page or rating filter

### ISSUE THREAD

**Issue by randolph24** [jobobby04/TachiyomiSY#63] opened 2020-07-18 13:52 UTC
### Device information
* Tachiyomi version: Preview r165
* Android version: 8.0.0
* Device: Samsung Galaxy S7 edge SM-G935F

## Steps to reproduce
1. As source select E-Hentai or ExHentai
2. Activate a page or rating filter 

### Expected behavior
Filtered results where each entry only appears once.

### Actual behavior
Some search results are duplicated and repeat. These are not different versions or translations, but really the same entries. This is also visible by the exactly identical upload date and the reading progress which changes in both entries simultaneously.

### Other details
![Screenshot_20200718-154036_TachiyomiSY](https://user-images.githubusercontent.com/68469969/87853946-8a958000-c90e-11ea-8c56-2456f70ee280.jpg)
![Screenshot_20200718-154050_TachiyomiSY](https://user-images.githubusercontent.com/68469969/87853948-8c5f4380-c90e-11ea-969e-fd182ff98c58.jpg)
![Screenshot_20200718-154107_TachiyomiSY](https://user-images.githubusercontent.com/68469969/87853950-8cf7da00-c90e-11ea-9177-913be3f8eea5.jpg)

**Comment by jobobby04** [comment] 2020-07-30 03:33
I cannot reproduce, if you continue to get this error in the next version of the app you can notify me and I will reopen this

**Comment by randolph24** [comment] 2020-07-30 21:32
I tried it again with the newest preview(184) and the bug still persists. I also tried it with two different device and there the bug also appears. The bug also is around a long time. It already apeared in TachiEH and TachAZ. It would be nice if the bug could be fixed eventually, because at the moment the ratings filter and pages filter are not very useful becaise of it.

![Screenshot_20200730-232033_TachiyomiSY](https://user-images.githubusercontent.com/68469969/88976615-a27ce480-d2bc-11ea-864f-e9bb047c2233.jpg)
![Screenshot_20200730-231837_TachiyomiSY](https://user-images.githubusercontent.com/68469969/88976620-a4df3e80-d2bc-11ea-843b-a2794539558e.jpg)

**Comment by joseph619** [comment] 2020-10-19 17:53
Can you try again and see if it persists?

**Comment by crisalis2** [comment] 2020-12-21 11:37
This has also happened to me for a long time. If you try more specific searches, and restricted to a single language, it will be easier to reproduce it and detect it.

**Comment by joseph619** [comment] 2021-03-28 20:15
@randolph24 @crisalis2 Does this still happen for you?

**Comment by crisalis2** [comment] 2021-03-28 23:28
I installed the latest preview and it still happens. For example, selecting only the "Non-H" genre and setting the Minimum Pages (this is important) to 50, I get this:
![image](https://user-images.githubusercontent.com/65630147/112771802-e8e23900-902d-11eb-8494-31ef0130fd7d.jpg)

**Comment by jondoe2021** [comment] 2021-03-29 06:03
I am also able to reproduce this issue. This is a valid bug. Please fix.

**Comment by jobobby04** [comment] 2021-05-21 21:38
I found why duplicate results show in E/ExHentai search, if your watched filters filter out more then 25 results on any search, it combines 2 pages together, but SY doesnt know it did that, so if it combined pages 2 and 3, SY would still request 3 

![nsbgflQ 1](https://user-images.githubusercontent.com/17078382/119200657-5b362f00-ba5b-11eb-8596-1638bacf3e8a.png)

**Comment by jobobby04** [comment] 2021-05-21 21:46
Actually its a bit different, but similar, they do a hacky thing that forces the page to only show 25 results, all the time, by combining the results from the next page into this one, and adding a &from parameter to the next page for the last gallery of this page

**Comment by joseph619** [comment] 2021-06-15 06:06
Apparently EhViewer fixed it, but a fix would require duplicate dirty code. For reference (from Discord)

https://github.com/seven332/EhViewer/commit/8b76eaa74004b55e34087746876e497f4771769e

**Comment by jobobby04** [comment] 2022-01-16 01:01
Finally got around to making a fix for this, will be included in the next build

**Comment by jobobby04** [comment] 2022-01-23 00:11
Addressed by https://github.com/jobobby04/TachiyomiSY/commit/e8100fc95876dc7eda40738433436e8c686250b2

**Closed** 2022-01-31 23:46 UTC
Labels: Bug, Will close next release
