### ISSUE TITLE
Please fix ram management 

### ISSUE THREAD

**Issue by mozzaru** [jobobby04/TachiyomiSY#1024] opened 2024-01-16 11:39 UTC
### Steps to reproduce

When the tachi apk I was reading a comic then opened the browser then returned to tchi ​​I lng relog or returned to the beginning

### Expected behavior

Please fix thanks 

### Actual behavior

Please fix 

### Crash logs

.

### Tachiyomi version

Last

### Android version

Android 11

### Device

Realme 7i

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ehsan18t** [comment] 2024-01-18 06:59
Not gonna lie, the RAM management become really bad from **Tachiyomi v0.15.0**. SY and Mihon and all other forks that are based on that version became the same. Most of the time when I read for a long time the app closes everything except for the chapter I was reading. Which might not seem a issue but it loads if I try going back.


This issue started from the **preview** state. I can't remember the exact version but I thought I will be fixed before the stable release. Then Kakao started spreading shits. I just hope this issue fixed soon. I would've stick with the [TachiyomiSY 1.9.4](https://github.com/jobobby04/TachiyomiSY/releases/tag/1.9.4) if only we didn't have to add custom extension repo. This version works flawlessly except the extension repo issue.

**Comment by mozzaru** [comment] 2024-01-18 07:04
I think I found it using the yokai base tachij2k apk

Pada Kam, 18 Jan 2024 13.59, Ehsan Khan ***@***.***> menulis:

**Comment by mozzaru** [comment] 2024-01-24 13:37
Maybe, but in the old version, you have to update the extension manually, especially since there are so many extensions, it's a bit of a hassle 😁

**Comment by ehsan18t** [comment] 2024-01-25 08:26
> but in the old version, you have to update the extension manually

IDk, what do you mean by this but for me (using Android 10) nothing related extension (except repo) has changed.

**Comment by mozzaru** [comment] 2024-01-25 08:59
What this means is that if you use the old version, you have to have 2 other apks so that the apk extension continues to be updated hahaha

**Comment by ehsan18t** [comment] 2024-01-25 09:05
2 other apks? 😕

**Comment by mozzaru** [comment] 2024-01-25 09:18
Like my old apk and mihon or j2k wkwk

**Comment by ehsan18t** [comment] 2024-01-25 09:20
I see what you mean. The old version doesnt support external repo. Yeah, and thats literally the reason I am using the new version.

**Comment by jobobby04** [comment] 2024-05-05 03:10
Duplicate of #1024

**Closed by jobobby04** 2024-05-05 03:10 UTC
Labels: Bug
